- id: '1674994585566'
  alias: Push configuration to Github daily
  description: ''
  triggers:
  - at: 05:05:05
    trigger: time
  conditions: []
  actions:
  - data: {}
    action: shell_command.pushupdates_to_github
  mode: single
- id: '1688668153520'
  alias: Synchronize Velbus time daily & on boot
  description: Synchronize the clock of the Velbus modules to the clock of the Home
    Assistant machine. Also run this automation after Home Assistant boots (in case
    the whole system has been power-cycled, the Velbus VMBELO module starts up without
    clock)
  triggers:
  - at: 03:30:00
    trigger: time
  - event: start
    trigger: homeassistant
  conditions: []
  actions:
  - data:
      interface: /dev/serial/by-id/usb-Velleman_Projects_VMB1USB_Velbus_USB_interface-if00
    action: velbus.sync_clock
  mode: single
- id: '1688672038200'
  alias: Blinds down at night
  description: ''
  triggers:
  - event: sunset
    offset: 00:30:00
    trigger: sun
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: cover.all_covers
    action: cover.close_cover
  mode: single
- id: '1688672230682'
  alias: Turn night lights off at sunset
  description: ''
  triggers:
  - event: sunrise
    offset: 0
    trigger: sun
  conditions: []
  actions:
  - data: {}
    target:
      entity_id:
      - light.ledstrip_achter_tv_beneden
      - light.ledstrip_achter_tv_boven
      - light.ledstrip_grote_venster_living
      - light.ledstrip_living_kant_keuken
      - light.ledstrip_nieuwbouw_bureau
      - light.vooraan_licht
    action: light.turn_off
  mode: single
- id: '1689693395970'
  alias: Low battery level detection
  description: Low battery level detection & notification for all battery sensors
  use_blueprint:
    path: Marck/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.i4_edrive40_remaining_battery_percent
        - number.i4_edrive40_target_soc
        - sensor.pixel_7_battery_level
        - binary_sensor.bureau_sensor_battery_low
        - sensor.ikea_of_sweden_kadrilj_roller_blind_battery
      actions:
      - service: notify.mobile_app_pixel_7
        data:
          title: Batterij leeg!
          message: Batterij moet gecheckt worden!
- id: '1690674892785'
  alias: Activate night lighting on office night scene selection
  description: Activate night lighting when pressing the sleep mode button on the
    office touch panel
  triggers:
  - entity_id:
    - binary_sensor.bureau_knop_3
    to: 'on'
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id: scene.night_lighting
    metadata: {}
    action: scene.turn_on
  mode: single
- id: '1691050249352'
  alias: Laptop camera in use triggers warning light
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.filip_macbook_16_camera_in_use
    trigger: state
  conditions:
  - condition: zone
    entity_id: person.filip
    zone: zone.home
  actions:
  - data: {}
    target:
      entity_id: switch.relay_4
    action: switch.turn_{{ trigger.to_state.state }}
  mode: single
- id: '1691268237350'
  alias: Open/Close Mezzanine Cover With White Ikea Remote
  description: ''
  use_blueprint:
    path: filipmaelbrancke/zha_ikea_tradfri_2button_remote_open_close.yaml
    input:
      remote: f0bfe057afe709a08b74026c46a05d91
      cover:
        entity_id: cover.ikea_of_sweden_kadrilj_roller_blind_cover
- id: '1691349871063'
  alias: Network - Re-enable Pi-hole after 15 minutes
  description: ''
  triggers:
  - entity_id:
    - switch.pi_hole
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
    trigger: state
  conditions:
  - condition: state
    entity_id: switch.pi_hole
    state: 'off'
  actions:
  - data: {}
    target:
      entity_id: switch.pi_hole
    action: homeassistant.turn_on
  mode: single
- id: '1707012933365'
  alias: Black button single click office white
  description: ''
  triggers:
  - device_id: 8b9b7e299695b19214719f71c886198d
    domain: shelly
    type: single
    subtype: button
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data:
      rgb_color:
      - 139
      - 39
      - 39
      brightness_pct: 50
    target:
      entity_id: light.ledstrip_nieuwbouw_bureau
    action: light.turn_on
  mode: single
- id: '1707012982534'
  alias: Black button long click office out
  description: ''
  triggers:
  - device_id: 8b9b7e299695b19214719f71c886198d
    domain: shelly
    type: long
    subtype: button
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: light.wit_bureau
    action: light.turn_off
  - metadata: {}
    data: {}
    target:
      entity_id: light.ledstrip_nieuwbouw_bureau
    action: light.turn_off
  mode: single
- id: '1711431821084'
  alias: Office outside door opened
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.bureau_sensor_contact
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data:
      message: Bureau deur open
      title: Bureau deur open
    action: notify.mobile_app_pixel_7
  - metadata: {}
    data:
      message: Bureau deur open
      title: Bureau deur open
    enabled: false
    action: notify.mobile_app_trees_pixel_6a
  mode: single
- id: '1711432807017'
  alias: "\U0001F6AA Office door contact sensor detected open notification"
  description: ''
  use_blueprint:
    path: Raukze/contact-sensor-left-open-notification.yaml
    input:
      trigger_entity: binary_sensor.bureau_sensor_contact
      friendly_name: Bureau buitendeur
      duration_issue_state:
        hours: 0
        minutes: 5
        seconds: 0
        days: 0
      notify_services_string: notify.mobile_app_pixel_7,notify.mobile_app_trees_pixel_6a
      notification_title: De {{ friendly_name }} is open gebleven
      notification_message: De {{ friendly_name }} was open gelaten om {{ as_timestamp(now())
        | timestamp_custom('%T', True) }}.
- id: '1714334623657'
  alias: Activate terras flood lighting when motion is detected
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.terras_bewegingssensor_input
      light_target:
        entity_id: light.terras_licht
- id: '1714597255332'
  alias: Activate front door lighting when motion is detected
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      light_target:
        entity_id: light.voordeur_licht
      motion_entity: binary_sensor.voordeur_bewegingssensor_bij_nacht
      no_motion_wait: 60
- id: '1714920703592'
  alias: Open covers in the morning
  description: ''
  triggers:
  - event: sunrise
    offset: 00:01:00
    trigger: sun
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_badkamer
    enabled: true
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
    enabled: true
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_groot_venster
    enabled: true
    action: cover.open_cover
  - metadata: {}
    data:
      position: 35
    target:
      entity_id: cover.rolluik_groot_venster
    action: cover.set_cover_position
    enabled: false
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_klein_venster
    enabled: true
    action: cover.open_cover
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_mezzanin
    enabled: true
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: true
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_mezzanin
    enabled: true
    action: cover.stop_cover
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_links
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 23
      milliseconds: 500
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_links
    action: cover.stop_cover
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_links_midden
    enabled: true
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 23
      milliseconds: 0
    enabled: true
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_links_midden
    enabled: true
    action: cover.stop_cover
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_rechts_midden
    enabled: true
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 22
      milliseconds: 500
    enabled: true
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_rechts_midden
    enabled: true
    action: cover.stop_cover
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_rechts
    enabled: true
    action: cover.open_cover
  - delay:
      hours: 0
      minutes: 0
      seconds: 24
      milliseconds: 0
    enabled: true
  - metadata: {}
    data: {}
    target:
      entity_id: cover.rolluik_bureau_rechts
    enabled: true
    action: cover.stop_cover
  mode: single
- id: '1716203089402'
  alias: Garbage pickup reminder
  description: ''
  triggers:
  - hours: '20'
    minutes: '00'
    seconds: '00'
    trigger: time_pattern
  conditions:
  - condition: template
    value_template: "\n{% if is_state(\"sensor.recycleapp_tomorrow\", \"None\") -%}\n
      \ false\n{%- else -%}\n  true\n{%- endif %}"
  actions:
  - metadata: {}
    data:
      title: Garbage reminder
      message: 'The following garbage will be picked up tomorrow: {{ states.sensor.recycleapp_tomorrow.state
        }}'
      data:
        url: /dashboard-home/0
        clickAction: /dashboard-home/0
        color: '#2DF56D'
        channel: Garbage
        importance: high
        visibility: public
    action: notify.mobile_app_pixel_7
  - metadata: {}
    data:
      title: Vuilnisophaling!
      message: 'Morgen wordt er vuilnis opgehaald: {{ states.sensor.recycleapp_tomorrow.state
        }}'
      data:
        url: /dashboard-home/0
        clickAction: /dashboard-home/0
        color: '#2DF56D'
        channel: Garbage
        importance: high
        visibility: public
    action: notify.mobile_app_trees_pixel_6a
    enabled: true
  mode: single
- id: '1725028344599'
  alias: Office Desk light following occupancy detection
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.everything_presence_one_occupancy
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.everything_presence_one_occupancy
        state: 'on'
      sequence:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e14_cws_globe_806lm_light
    - conditions:
      - condition: state
        entity_id: binary_sensor.everything_presence_one_occupancy
        state: 'off'
      sequence:
      - delay:
          hours: 0
          minutes: 2
          seconds: 0
          milliseconds: 0
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e14_cws_globe_806lm_light
  mode: restart
- id: '1729003433307'
  alias: Bathroom extra heat
  description: ''
  use_blueprint:
    path: filipmaelbrancke/scheduled_switching.yaml
    input:
      schedule_entity: schedule.bathroom_extra_heating
      switch_target:
        entity_id: switch.badkamer
