- id: '1674994585566'
  alias: Push configuration to Github daily
  description: ''
  trigger:
  - platform: time
    at: 05:05:05
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1688668153520'
  alias: Synchronize Velbus time daily & on boot
  description: Synchronize the clock of the Velbus modules to the clock of the Home
    Assistant machine. Also run this automation after Home Assistant boots (in case
    the whole system has been power-cycled, the Velbus VMBELO module starts up without
    clock)
  trigger:
  - platform: time
    at: 03:30:00
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: velbus.sync_clock
    data:
      interface: /dev/serial/by-id/usb-Velleman_Projects_VMB1USB_Velbus_USB_interface-if00
  mode: single
- id: '1688672038200'
  alias: Blinds down at night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:30:00
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.all_covers
  mode: single
- id: '1688672230682'
  alias: Turn ledstrips off at sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.ledstrip_achter_tv_beneden
      - light.ledstrip_achter_tv_boven
      - light.ledstrip_grote_venster_living
      - light.ledstrip_living_kant_keuken
      - light.ledstrip_nieuwbouw_bureau
  mode: single
- id: '1689693395970'
  alias: Low battery level detection
  description: Low battery level detection & notification for all battery sensors
  use_blueprint:
    path: Marck/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.i4_edrive40_remaining_battery_percent
        - number.i4_edrive40_target_soc
        - sensor.pixel_7_battery_level
        - binary_sensor.bureau_sensor_battery_low
        - sensor.ikea_of_sweden_kadrilj_roller_blind_battery
      actions:
      - service: notify.mobile_app_pixel_7
        data:
          title: Batterij leeg!
          message: Batterij moet gecheckt worden!
- id: '1690674892785'
  alias: Activate night lighting on office night scene selection
  description: Activate night lighting when pressing the sleep mode button on the
    office touch panel
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bureau_knop_3
    to: 'on'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.night_lighting
    metadata: {}
  mode: single
- id: '1690755948562'
  alias: Open office covers in the morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.office_covers
  - delay:
      hours: 0
      minutes: 0
      seconds: 6
      milliseconds: 0
  - service: cover.stop_cover
    data: {}
    target:
      entity_id: cover.office_covers
  mode: single
- id: '1691050249352'
  alias: Laptop camera in use triggers warning light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.filip_macbook_16_camera_in_use
  condition:
  - condition: zone
    entity_id: person.filip
    zone: zone.home
  action:
  - service: switch.turn_{{ trigger.to_state.state }}
    data: {}
    target:
      entity_id: switch.relay_4
  mode: single
- id: '1691268237350'
  alias: Open/Close Mezzanine Cover With White Ikea Remote
  description: ''
  use_blueprint:
    path: filipmaelbrancke/zha_ikea_tradfri_2button_remote_open_close.yaml
    input:
      remote: f0bfe057afe709a08b74026c46a05d91
      cover:
        entity_id: cover.ikea_of_sweden_kadrilj_roller_blind_cover
- id: '1691349871063'
  alias: Network - Re-enable Pi-hole after 15 minutes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pi_hole
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: switch.pi_hole
    state: 'off'
  action:
  - service: homeassistant.turn_on
    data: {}
    target:
      entity_id: switch.pi_hole
  mode: single
- id: '1695419779400'
  alias: Bathroom extra heat
  description: ''
  use_blueprint:
    path: filipmaelbrancke/scheduled_switching.yaml
    input:
      schedule_entity: schedule.bathroom_extra_heating
      switch_target:
        entity_id: switch.badkamer
- id: '1703370671595'
  alias: black shelly short touch turn on ledstrip
  description: ''
  trigger:
  - platform: device
    device_id: 8b9b7e299695b19214719f71c886198d
    domain: shelly
    type: single
    subtype: button
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.wit_bureau
    data: {}
  mode: single
- id: '1703370719325'
  alias: black shelly long touch turn off ledstrip
  description: ''
  trigger:
  - platform: device
    device_id: 8b9b7e299695b19214719f71c886198d
    domain: shelly
    type: long
    subtype: button
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.wit_bureau
    data: {}
  mode: single
