- id: '1674994585566'
  alias: Push configuration to Github daily
  description: ''
  trigger:
  - platform: time
    at: 05:05:05
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1688668153520'
  alias: Synchronize Velbus time daily & on boot
  description: Synchronize the clock of the Velbus modules to the clock of the Home
    Assistant machine. Also run this automation after Home Assistant boots (in case
    the whole system has been power-cycled, the Velbus VMBELO module starts up without
    clock)
  trigger:
  - platform: time
    at: 03:30:00
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: velbus.sync_clock
    data:
      interface: /dev/serial/by-id/usb-Velleman_Projects_VMB1USB_Velbus_USB_interface-if00
  mode: single
- id: '1688672038200'
  alias: Blinds down at night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:10:00
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.all_covers
  mode: single
- id: '1688672230682'
  alias: Turn ledstrips off at sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.ledstrip_achter_tv_beneden
      - light.ledstrip_achter_tv_boven
      - light.ledstrip_grote_venster_living
      - light.ledstrip_living_kant_keuken
      - light.ledstrip_nieuwbouw_bureau
  mode: single
- id: '1689693395970'
  alias: Low battery level detection
  description: Low battery level detection & notification for all battery sensors
  use_blueprint:
    path: Marck/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.i4_edrive40_remaining_battery_percent
        - number.i4_edrive40_target_soc
        - sensor.pixel_7_battery_level
        - binary_sensor.bureau_sensor_battery_low
      actions:
      - service: notify.mobile_app_pixel_7
        data:
          title: Batterij leeg!
          message: Batterij moet gecheckt worden!
- id: '1690674892785'
  alias: Activate night lighting on office night scene selection
  description: Activate night lighting when pressing the sleep mode button on the
    office touch panel
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bureau_knop_3
    to: 'on'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.night_lighting
    metadata: {}
  mode: single
- id: '1690755948562'
  alias: Open office covers in the morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.office_covers
  - delay:
      hours: 0
      minutes: 0
      seconds: 6
      milliseconds: 0
  - service: cover.stop_cover
    data: {}
    target:
      entity_id: cover.office_covers
  mode: single
- id: '1690978867682'
  alias: Open/Close Mezzanine Cover With White Ikea Remote
  description: ''
  use_blueprint:
    path: filipmaelbrancke/zha_ikea_tradfri_2button_remote_open_close.yaml
    input:
      remote: f0bfe057afe709a08b74026c46a05d91
      cover:
        entity_id: cover.ikea_of_sweden_kadrilj_roller_blind_cover
