# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh

sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary-sensor
command_line: !include devices/command-line.yaml
cover: !include devices/cover.yaml
group: !include group/groups.yaml

logger: !include logger.yaml

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_75830333439351E07090-if00
# https://www.home-assistant.io/integrations/zha/#ota-updates-of-zigbee-device-firmware
# should be enabled by default
# zha:
#   zigpy_config:
#     ota:
#       ikea_provider: true # Auto update Trådfri devices

adaptive_lighting:
  separate_turn_on_commands: true
  send_split_delay: 100
  min_brightness: 15
  max_brightness: 90
  lights:
    - light.ikea_of_sweden_tradfri_bulb_e14_cws_globe_806lm_light
