blueprint:
  source_url: https://github.com/filipmaelbrancke/home-assistant/blob/master/blueprints/automation/filipmaelbrancke/scheduled_switching.yaml
  name: Schedule-activated Switch
  description: This automation turns a switch on and off following a schedule.
  domain: automation
  input:
    schedule_entity:
      name: Schedule
      description: Select the schedule you wish to follow
      selector:
        entity:
          domain:
          - schedule
          multiple: false
    switch_target:
      name: Switch
      description: The switch that needs to follow the schedule
      selector:
        target:
          entity:
          - domain:
            - switch
trigger:
- platform: state
  entity_id: !input schedule_entity
action:
- service: homeassistant.turn_{{ trigger.to_state.state }}
  target: !input switch_target
mode: single
