---
# This automation simulates the use of the IKEA TRADFRI Open/Close control
# connected through ZHA.
# Manufacturer for mine is listed as 'KE', not 'IKEA of Sweden' as all other Tradfri devices
# see https://github.com/home-assistant/core/issues/46488
# Inspiration:
# https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_2button_remote_custom.yaml
# https://community.home-assistant.io/t/deconz-ikea-open-close-remote/265819

blueprint:
  source_url: https://github.com/filipmaelbrancke/home-assistant/blob/master/blueprints/automation/filipmaelbrancke/zha_ikea_tradfri_2button_remote_open_close.yaml

  name: ZHA - IKEA TRADFRI - 2 Button Open/Close Remote - Custom Actions

  description: >-
    This automation simulates the use of the IKEA TRADFRI open/close switch
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use
      selector:
        device:
          integration: zha
          # manufacturer: KE
          model: TRADFRI open/close remote
    up_short:
      name: Short Press - Up Button
      description: The action to perform on Short Press of the Up Button
      selector:
        action:
      default: []
    down_short:
      name: Short Press - Down Button
      description: The action to perform on Short Press of the Down Button
      selector:
        action:
      default: []
    up_long:
      name: Long Press - Up Button
      description: The action to perform on Long Press of the Up Button
      selector:
        action:
      default: []
    down_long:
      name: Long Press - Down Button
      description: The action to perform on Long Press of the Down Button
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press the up button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "up_open" }}'
        sequence: !input up_short

      # Long-Press the up button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_opening" }}'
        sequence: !input up_long

      # Short-Press the down button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "down_close" }}'
        sequence: !input down_short

      # Long-Press the down button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_closing" }}'
        sequence: !input down_long

    # Any other event will cancel the repeat loops (i.e. releasing the [up|down] button)
    default: []
