- platform: template
  sensors:
    garage_door_opened_sensor:
      friendly_name: "Garage Door Opened Sensor"
      delay_on:
        seconds: 4
      delay_off:
        seconds: 4
      value_template: >
        {{ is_state('binary_sensor.bthome_sensor_1806_window', 'on') }}
