- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: "Config last backup"
  command: cd /config && git --no-pager log -n 1 --pretty=%cd --date=local origin/master
  scan_interval: 60
